### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Nbjohnston86** [warriordog/ActivityPubSharp#1]
Hello!

I recently became interested in the fediverse concept, and learned about the underlying protocols (ActivityPub/WebFinger) under which Mastodon relies. I was curious if the .net ecosystem had any implementation of ActivityPub. This is one of two repositories I've found, both without a license. This repository is more recent, and is more in line with an implementation that I was considering myself, so I was considering contributing instead of starting from scratch. 

But without a license, I cannot safely do so. I see that adding an open source license is on your To-Do list already, but I figured adding an issue might encourage you to do it sooner rather than later. 🙂

If you're your having difficulty deciding which license to use, I'm more than happy to discuss it with you.

**Comment by warriordog** [comment]
Hello! I can certainly add a license if you're interested in using this code, but please keep in mind that this is nowhere near production-ready! I've kind of hit a snag with JSON-LD support and I don't (currently) have much time to work on it, so it will be a while before there's any more progress.

Additionally, I'm still mulling on the correct way to handle the multiple different "flavors" of ActivityPub that are actively used today. I've got multiple solutions in mind, but none of them are particularly great.

But if you'd like to contribute or use the code anyway, then I'd be glad to add a license! I'll probably go with a permissive OSS license.

**Comment by Nbjohnston86** [comment]
Yes, I would like to help, time permitting. I like the idea behind activity pub, and would like for it to be accessible to more developers. It was pretty surprising to find that it barely existed in the .NET space.

If you're stuck, I can definitely give my input to help the project along. But a license is definitely the first step.

It may be outside the scope of this issue, but my long-term goal is to have this integrate nicely with ASP.NET MVC and/or Razor Pages. Making this standard accessible is really important to it's adoption. 

Let me know when and how I can help.

**Comment by warriordog** [comment]
@Nbjohnston86 I appreciate the interest in this! I've been quite frustrated with the lack of .NET libraries for ActivityPub and related technologies. I've *also* been frustrated with all the suggestions to "just use a different platform" :roll_eyes:

I could use some help picking a license. I'd like to use a weakly-copyleft license like the LGPL, but I also want to allow static-linking against ActivityPubSharp. Basically, I want to prevent someone from creating a closed-source fork of this library *without* preventing anyone from including it in a larger closed-source Fediverse project. **Firstly, does this sound reasonable?** And secondly, can you think of any license that fills this case? I've considered the MPL but it has various issues that make it undesirable.

> It may be outside the scope of this issue, but my long-term goal is to have this integrate nicely with ASP.NET MVC and/or Razor Pages. Making this standard accessible is really important to it's adoption.

I have the same goal, actually. I'd like to build this library in a modular fashion so that a project can include exactly the components that it cares about. Then, it would be trivial to create an integration package that supports ASP.NET without requiring all downstream applications to use that framework.

**Comment by Nbjohnston86** [comment]
I definitely understand the difficulty in choosing between the two of them. I actually read up on these licenses a couple of days ago to understand their nuances.

My research brought me to this discussion:
https://softwareengineering.stackexchange.com/questions/179084/is-there-a-modified-lgpl-license-that-allows-static-linking


Based upon that discussion, I have a couple of thoughts and a question.

My first thought is, LGPL may not be as limiting as you think. When reading a discussion about how to use LGPL code can be used in something more proprietary, I've seen a discussion about accessing the dynamically loaded library with _shims_. That way, the derivative library can still technically it's own thing while being extended for extra functionality. If this is the approach you decide upon, you could make it part of the design philosophy to make as much of the project to allow as much inheritance and extensibility as you can, so that this is easy to accomplish.

My second thought you could use the wxWindows Library License, as mentioned in that discussion, which I believe is essentially what you want. The problem with this, however, is that it is a lesser known license, and my gut feeling on that is that people wouldn't want to use a license that isn't as "battle-tested" or as well understood as MPL and LGPL are, so that could keep some from using it, even if it was safe to do so.

And lastly, my question: What are your reservations about the MPL? Knowing this can help me understand the dilemma a little better.

**Comment by warriordog** [comment]
@Nbjohnston86 Thanks for the response!

> My first thought is, LGPL may not be as limiting as you think. When reading a discussion about how to use LGPL code can be used in something more proprietary, I've seen a discussion about accessing the dynamically loaded library with shims. That way, the derivative library can still technically be it's own thing while being extended for extra functionality. If this is the approach you decide upon, you could make it part of the design philosophy to make as much of the project to allow as much inheritance and extensibility as you can, so that this is easy to accomplish.

That's an interesting thought. I am planning for the library to be used largely through DI, which would help decouple the code. But my concern is mostly for .NET single-file executables that are (essentially) statically linked. You could theoretically load an alternate version of the library from an external DLL, but that burden would fall entirely onto the developer of the larger application. I'd prefer for this to be easy to use since one of my goals is to encourage development of fediverse software.

> My second thought you could use the wxWindows Library License, as mentioned in that discussion, which I believe is essentially what you want. The problem with this, however, is that it is a lesser known license, and my gut feeling on that is that people wouldn't want to use a license that isn't as "battle-tested" or as well understood as MPL and LGPL are, so that could keep some from using it, even if it was safe to do so.

I'll look into that, but I'd prefer to use a well-known license for the reasons you listed.

> And lastly, my question: What are your reservations about the MPL? Knowing this can help me understand the dilemma a little better.

So apparently, I was looking at the MPL version 1.1 which is not the latest. :woman_facepalming: MPL 2 seems way better and is probably the best choice tbh.

**Comment by warriordog** [comment]
I've licensed the code base under MPL 2.0. I'll go back through and add the copyright header to existing files
